---
title: "Homework 3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T,eval=T,message=F,warning=F,fig.align='center')
library(tidyverse)
```

## 1. Independence of Events <small>(8 points, 2 points each)</small>

A fair four-sided die (numbered 1,2,3 and 4) is rolled three times. Consider the following three events:

A: "The sum is 6 or less"

B: "The second roll is more than the first"

C: "The sum is odd"

D: "Exactly two of the rolls are the same"

a. Are A and B independent?
b. Are C and D independent?
c. Are A and C independent?
d. Are B and D independent?


## 2. Stock Portfolio <small>(8 points, 2 points each)</small>

Consider two stocks. Stock A has a mean annual return of 0.05 and a standard deviation of 0.01. Stock B has a mean annual return of 0.10 and a standard deviation of 0.04. Past data suggests that the prices have a correlation of -0.65.
You have \$1000 to invest in a portfolio composed of these two stocks. 

a. Suppose you invest \$500 in stock A and \$500 in stock B. What will be the expected return and the standard deviation of your portfolio (in dollars)? 
*Hint:* $SD(aX+bY) = \sqrt{Var(aX+bY)}= \sqrt{a^2Var(X)+2abCov(X,Y)+b^2Var(Y)}$ and $Cov(X,Y)=\sigma_X \sigma_Y \rho_{XY}$

b. Give an expression for the standard deviation for a portfolio investing $\$x$ in stock A and $\$1000-x$ in stock B. 

c. Find the value $x$ that minimizes this standard deviation. 

d. What is the expected return and standard deviation (in dollars) for the portfolio split you chose in part c?



## 3. Mousetrap: A Rube Goldberg Machine  <small>(5 points, 1 points each)</small>

Consider the board game Mousetrap. When you trigger the trap, the ball needs to 

1. roll down a **ramp**,
2. be carried up by a **hammer**,
3. roll  down another **ramp**,
4. go down a bathtub **drain**,
5. land on a **lever** which
6. sends a diver into a **basin** which then
7. causes the **trap** to descend.

Suppose you can model the success of each component as independent Bernoulli random variables $X_1$ through $X_7$, where the probability of $X_i$ succeeding is $.94$ for each component. 

a. What is the probability that the trap works correctly from beginning to end?

b. If you attempt the trap 15 times during a game, how many times do you expect it to work correctly from beginning to end?

c. Suppose you let the marble go: Let $Y$ be the number of components of the trap that work in a row. If one component fails, then you stop counting. Calculate the probability mass function of $Y$. *Hints: $Y$ can have values $0, 1, 2, 3, 4, 5, 6$ or $7$. This is like a Geometric r.v. except it does not have infinite support. How can you use this fact to determine the pmf? Be careful: what is a 'success' in this context?*

d. Calculate the expected value of $Y$ and its variance. 

e. What is $P(Y = 6 | Y \geq 3)$?



## 4. Bayes Rule with forecasting <small>(9 points, 3 points each)</small>

Madison, Wisconsin gets about 115 days of precipitation per year (we'll just call it rain for the remainder of this problem, even though it is often snow). On days when it ends up raining the forecast on Channel 3000 is correct (i.e. the morning forecast calls for rain) 93% of the time. On days where there is no rain the morning forecast correctly says there will be no rain 87% of the time. 

a. Calculate the overall probability that a forecast on a randomly selected day is correct.

b. If the weather from day to day is independent and the forecast accuracy from day to day is independent, then how many correctly forecasted days do you expect in a 365 day year? 

c. If the forecast calls for rain, what is the likelihood that it actually rains? In other words, find $P(\text{Rain} | \text{Forecast Rain})$.


